project:
  type: book
  output-dir: docs

book:
  title: "Derya Şaşmaz Progress Journal"
  repo-url: https://github.com/pjournal/mef07-sasmazd
  chapters:
    - index.qmd
    - assignment1.qmd
    - inClass.qmd
    - inClass2.qmd
    - assignment_shiny.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo

